theme: jekyll-theme-cayman

# Site basics
name: Anurag Bhatt
description: Code. Games. Chaos. Documenting the ride until I get a job.
avatar: https://avatars.githubusercontent.com/u/70936447?v=4

# Social icons in footer
footer-links:
  github: Anurag-Bhatt
  linkedin: https://www.linkedin.com/in/anuragbhatt1911/
  rss: true

# Optional 
disqus: 
google_analytics:

# URL of your GitHub Pages site
url: "https://anurag-bhatt.github.io"
baseurl: "/anurag-devlog"

# Blog post permalink structure
permalink: /:title/

# Theme config
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
